# Generated by Django 4.0.6 on 2022-08-16 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('tipo_cliente', models.CharField(choices=[('C', 'Classic'), ('G', 'Gold'), ('B', 'Black')], default='C', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
